#!/usr/bin/env bash
set -euo pipefail
source "$GM_ROOT_DIR/lib/common.sh"
source "$GM_ROOT_DIR/lib/hw.sh"

write_makeconf() {
  local gpu
  gpu=$(detect_gpu_vendor || echo unknown)

  local video_cards="amdgpu radeonsi"
  case "$gpu" in
    amd) video_cards="amdgpu radeonsi" ;;
    intel) video_cards="intel i965 iris" ;;
    nvidia) video_cards="nvidia" ;;
    *) video_cards="amdgpu radeonsi" ;;
  esac

  # CPU_FLAGS_X86 from cpuid2cpuflags
  local cpu_flags=""
  if command -v cpuid2cpuflags >/dev/null 2>&1; then
    cpu_flags=$(cpuid2cpuflags | tr '\n' ' ' | sed 's/CPU_FLAGS_X86: //')
  fi

  local nproc
  nproc=$(nproc || echo 4)

  cat > /etc/portage/make.conf <<EOF
# Generated by golden-master
ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"
FEATURES="\${FEATURES} parallel-fetch buildpkg"
MAKEOPTS="-j${nproc}"

# Toolchain: clang/lld (aggressive)
CC="clang"
CXX="clang++"
LD="ld.lld"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"

COMMON_FLAGS="-O2 -pipe -march=native -fuse-ld=lld"
CFLAGS="\${COMMON_FLAGS}"
CXXFLAGS="\${COMMON_FLAGS}"
FCFLAGS="\${COMMON_FLAGS}"
FFLAGS="\${COMMON_FLAGS}"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"

RUSTFLAGS="-C target-cpu=native"

# Graphics / input
VIDEO_CARDS="${video_cards}"
CPU_FLAGS_X86="${cpu_flags}"

# System preferences
GRUB_PLATFORMS=""
LINGUAS="en"
LC_MESSAGES=C.UTF-8

# QoL
EMERGE_DEFAULT_OPTS="--jobs=${nproc} --load-average=${nproc} --keep-going=y --with-bdeps=y"
EOF
}

enable_repos() {
  emerge --quiet-build=y app-eselect/eselect-repository || true
  eselect repository enable guru 2>/dev/null || true

  if [[ "${GM_KERNEL_STRATEGY:-bin}" == "cachyos" ]]; then
    eselect repository enable CachyOS-kernels 2>/dev/null || true
  fi

  # Steam overlay for steam-launcher (optional for gamemode)
  # https://github.com/anyc/steam-overlay
  if [[ ! -d /var/db/repos/steam-overlay ]]; then
    log "Adding steam-overlay…"
    mkdir -p /etc/portage/repos.conf
    cat > /etc/portage/repos.conf/steam-overlay.conf <<'EOF'
[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git
auto-sync = yes
EOF
  fi

  emaint sync -a || emerge --sync
}

run() {
  log "Configuring Portage and base packages…"

  # Ensure Portage tree is present
  emerge-webrsync || true
  enable_repos

  log "Installing toolchain + utilities…"
  emerge --quiet-build=y \
    sys-devel/llvm sys-devel/clang sys-devel/lld \
    app-portage/gentoolkit app-portage/eix \
    app-misc/cpuid2cpuflags \
    sys-fs/dosfstools sys-fs/cryptsetup sys-fs/btrfs-progs sys-fs/xfsprogs \
    app-arch/zstd app-arch/lz4 app-arch/bzip2 \
    net-misc/curl dev-vcs/git \
    sys-process/htop sys-apps/pciutils || true

  write_makeconf

  # Portage directories
  mkdir -p /etc/portage/{package.use,package.accept_keywords,env,sets}

  # Prefer PipeWire and Wayland (safe defaults)
  cat > /etc/portage/package.use/00-gm-base <<'EOF'
media-video/pipewire sound-server
media-video/wireplumber
media-libs/mesa vulkan wayland
EOF

  eix-update || true
  log "Portage configured."
}
