#!/usr/bin/env bash
set -euo pipefail
source "$GM_ROOT_DIR/lib/common.sh"
source "$GM_ROOT_DIR/lib/hw.sh"

uuid_of() { blkid -s UUID -o value "$1"; }
partuuid_of() { blkid -s PARTUUID -o value "$1"; }

has_bin() { [[ " ${GM_BINPKGS:-} " == *" $1 "* ]]; }

write_fstab() {
  local efi_part="$GM_EFI_PART"
  local rootdev="$GM_ROOTDEV"
  local fs="$GM_FS"
  local f=/etc/fstab
  : > "$f"

  echo "# /etc/fstab - generated by golden-master" >>"$f"
  echo "UUID=$(uuid_of "$efi_part")  /boot  vfat  noatime  0 2" >>"$f"

  if [[ "$fs" == "btrfs" ]]; then
    local root_uuid
    root_uuid=$(uuid_of "$rootdev")
    echo "UUID=$root_uuid  /          btrfs  noatime,ssd,compress=zstd:3,space_cache=v2,subvol=@  0 1" >>"$f"
    echo "UUID=$root_uuid  /home      btrfs  noatime,ssd,compress=zstd:3,space_cache=v2,subvol=@home 0 2" >>"$f"
    echo "UUID=$root_uuid  /var       btrfs  noatime,ssd,compress=zstd:3,space_cache=v2,subvol=@var  0 2" >>"$f"
    echo "UUID=$root_uuid  /steam     btrfs  noatime,ssd,compress=zstd:1,space_cache=v2,subvol=@steam 0 2" >>"$f"
    echo "UUID=$root_uuid  /.snapshots btrfs noatime,ssd,compress=zstd:3,space_cache=v2,subvol=@snapshots 0 2" >>"$f"
  else
    echo "UUID=$(uuid_of "$rootdev")  /  $fs  noatime  0 1" >>"$f"
  fi
}

write_cmdline() {
  local fs="$GM_FS"
  local rootarg
  local cryptarg=""
  if [[ "$GM_ENCRYPTION" == "luks_tpm" || "$GM_ENCRYPTION" == "luks_pass" ]]; then
    rootarg="root=/dev/mapper/${GM_LUKS_NAME}"
    cryptarg="rd.luks.uuid=$(uuid_of "$GM_LUKS_DEV")"
  else
    rootarg="root=UUID=$(uuid_of "$GM_ROOTDEV")"
  fi

  local subvol=""
  if [[ "$fs" == "btrfs" ]]; then
    subvol="rootflags=subvol=@"
  fi

  cat > /etc/kernel/cmdline <<EOF
quiet splash ${cryptarg} ${rootarg} ${subvol} rw
EOF
}

setup_dracut() {
  emerge --quiet-build=y sys-kernel/dracut sys-kernel/installkernel || true
  mkdir -p /etc/dracut.conf.d
  cat > /etc/dracut.conf.d/00-gm.conf <<'EOF'
hostonly=yes
compress="zstd"
# Helpful for LUKS+TPM
add_dracutmodules+=" tpm2-tss "
EOF
}

setup_zram() {
  emerge --quiet-build=y sys-block/zram-generator || true
  local mem
  mem=$(mem_gib)
  mkdir -p /etc/systemd
  cat > /etc/systemd/zram-generator.conf <<EOF
[zram0]
zram-size = min(${mem}G, 16G)
compression-algorithm = zstd
swap-priority = 100
EOF
}

run() {
  log "Kernel + bootloader setup…"

  # Base systemd stack
  emerge --quiet-build=y sys-apps/systemd sys-apps/systemd-utils || true
  systemctl enable systemd-timesyncd || true

  # Networking (NetworkManager, optionally with iwd backend)
  if [[ "${GM_WIFI_BACKEND:-wpa}" == "iwd" ]]; then
    # Ensure NetworkManager is built with iwd support
    mkdir -p /etc/portage/package.use
    echo "net-misc/networkmanager iwd" >> /etc/portage/package.use/gm-networkmanager
    emerge --quiet-build=y net-wireless/iwd net-misc/networkmanager || true
    mkdir -p /etc/NetworkManager/conf.d
    cat > /etc/NetworkManager/conf.d/iwd.conf <<'EOF'
[device]
wifi.backend=iwd
EOF
    # Do not let iwd manage DHCP itself (NM should own config)
    mkdir -p /etc/iwd
    cat > /etc/iwd/main.conf <<'EOF'
[General]
EnableNetworkConfiguration=false
EOF
    systemctl enable --now iwd || true
    systemctl disable --now wpa_supplicant 2>/dev/null || true
    systemctl mask wpa_supplicant 2>/dev/null || true
  else
    emerge --quiet-build=y net-misc/networkmanager || true
  fi
  systemctl enable NetworkManager || true

  # Bluetooth
  if [[ "${GM_ENABLE_BT:-no}" == "yes" ]]; then
    emerge --quiet-build=y net-wireless/bluez || true
    systemctl enable bluetooth || true
  fi

  # Firmware microcode
  case "$(detect_cpu_vendor)" in
    amd) emerge --quiet-build=y sys-firmware/amd-ucode || true ;;
    intel) emerge --quiet-build=y sys-firmware/intel-microcode || true ;;
  esac

  # Bootable kernel package (fast fallback if chosen)
  local kernel_pkg="sys-kernel/gentoo-kernel-bin"
  if ! has_bin kernel-bin; then
    kernel_pkg="sys-kernel/gentoo-kernel"
  fi
  emerge --quiet-build=y "${kernel_pkg}" || die "Kernel install failed."
  setup_dracut

  # Build initramfs for the latest installed kernel
  local kver
  kver=$(ls -1 /lib/modules 2>/dev/null | sort -V | tail -n1 || true)
  if [[ -n "$kver" ]]; then
    dracut -f "/boot/initramfs-${kver}.img" "$kver" || true
  fi

  mkdir -p /etc/kernel
  write_cmdline

  # Install systemd-boot
  bootctl install || die "bootctl install failed."
  mkdir -p /boot/loader
  cat > /boot/loader/loader.conf <<EOF
default gentoo.conf
timeout $( [[ "${GM_PROFILE}" == "gamemode" ]] && echo 0 || echo 3 )
console-mode auto
editor no
EOF

  # installkernel should create BLS entries; ensure one exists
  if [[ ! -f /boot/loader/entries/gentoo.conf ]]; then
    # create a simple entry pointing to the latest vmlinuz
    local kimg initrd
    kimg=$(ls -1 /boot/vmlinuz-* 2>/dev/null | tail -n1 || true)
    initrd=$(ls -1 /boot/initramfs-* 2>/dev/null | tail -n1 || true)
    [[ -n "$kimg" ]] || die "Kernel image not found in /boot"
    cat > /boot/loader/entries/gentoo.conf <<EOF
title   Gentoo (Golden Master)
linux   $(basename "$kimg")
initrd  $(basename "$initrd")
options $(cat /etc/kernel/cmdline)
EOF
  fi

  write_fstab

  # crypttab for systemd in initramfs
  if [[ "$GM_ENCRYPTION" == "luks_tpm" || "$GM_ENCRYPTION" == "luks_pass" ]]; then
    local luks_uuid
    luks_uuid=$(uuid_of "$GM_LUKS_DEV")

    local opts="-"
    if [[ "$GM_ENCRYPTION" == "luks_tpm" ]]; then
      opts="tpm2-device=auto"
    fi

    cat > /etc/crypttab <<EOF
${GM_LUKS_NAME} UUID=${luks_uuid} - ${opts}
EOF
  fi

  setup_zram

  log "Kernel/boot configured."
}
